name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # runs once a day, midnight UTC
  workflow_dispatch: {} # lets you trigger it manually from the Actions tab
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate the 3D contribution calendar (github-action)
        uses: yoshi389111/github-profile-3d-contrib@v0.9.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Bekon0700

      - name: Push the generated files to the profile-3d branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: profile-3d
          build_dir: profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
