name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # runs once a day, midnight UTC
  workflow_dispatch: {} # lets you trigger it manually from the Actions tab
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate a snake game from a github user (github-action)
        uses: Platane/snk@v3
        with:
          github_user_name: Bekon0700
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#2f81f7&color_dots=#ebedf0,#9ec5ff,#58a6ff,#2f81f7,#1f6feb
            dist/github-contribution-grid-snake-dark.svg?color_snake=#58a6ff&color_dots=#161b22,#0a2647,#144272,#2f81f7,#58a6ff

      - name: Push the generated files to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}